// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtc4ke2ImJW8qsYgoTSTJzYi8s_xzJivo',
    appId: '1:635255404794:web:53b08e8f650e8ce6507143',
    messagingSenderId: '635255404794',
    projectId: 'quizlet-app-123',
    authDomain: 'quizlet-app-123.firebaseapp.com',
    storageBucket: 'quizlet-app-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm2nfxcrm1GjtCmVIMo_XHDGEZsLejXCU',
    appId: '1:635255404794:android:bbd8969eae76d088507143',
    messagingSenderId: '635255404794',
    projectId: 'quizlet-app-123',
    storageBucket: 'quizlet-app-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCslwbbYVw5j75240_awXwEvhn3cAISlHI',
    appId: '1:635255404794:ios:8d199088275fb74d507143',
    messagingSenderId: '635255404794',
    projectId: 'quizlet-app-123',
    storageBucket: 'quizlet-app-123.firebasestorage.app',
    androidClientId: '635255404794-vjl3rhskp8hon9a5h0virfd1aiuu1q4o.apps.googleusercontent.com',
    iosClientId: '635255404794-pa61bkkavum4j5771sofl88tbv4nu6no.apps.googleusercontent.com',
    iosBundleId: 'com.example.mad',
  );

}